### PR TITLE
macosx fixes

### PR DESCRIPTION
**Pull request by srandoux**
Hi, 
I had issues compiling on Yosemite (10.10).
In the cmake, I added the CoreFoundation Framework, and also my cmake understands EXTRA_LIBS and not EXTRALIBS else it can't find the framework. Maybe it is related to the version of cmake (3.x).

Then the serial porte has some issues:

tcsetattr(ttyDeviceFileDescriptor, TCSANOW, &tty) after speed change fails. I don't undersstand why you did it twice in the code. Once before the change of speed, one after.
Also, there and issue if the baud rate change happens to quickly after the attributes change, the read operatiosn do not return anything, not clear why... for the moment, I put a sleep and everything works as expected.

Don't know if you can test also on mac but these are the issues I had.

### CODE REVIEW

**Comment by emericg** [comment]
Hey!
Does this mean that the framework now works on OS X? That's great news!
Indeed I do not have much time to work and debug this code with a mac so I wasn't sure what to do about the remaining issues...
- I'll merge the CMakeFile stuff, it does seems to be an error from my part.
- The QMake file build the framework sources directly and does not link with the library "by design", as right now there is too much changes happening in the framework, and rebuilding the library every time would be too much of a hassle. (I think I can edit the pull request to remove those changes)
- It's very nice to have debugged this code, most of it was coming from the linux version, mixed with sample code from Apple. I don't recall why the tcsetattr was done twice either.

I'll merge this tonight at home, thanks!

**Comment by srandoux** [comment]
Yes, it works.
the main issue was really to understand why not read were happening and I found out that when change of baud speed happens to quickly avec the change of attributes, the read does not work. For the moment, I put a sleep of 1s which is really ugly and i'd like to find a proper way to fix that but for the moment it works... Then for pull request, it was really just to give feedbacks, you don't have to take it like that. Don't hesitate to ask me if you want some tests. It is always good to have a working mac version along with the linux one.

**Comment by emericg** [comment]
Yeah a Mac OS version is really nice. Regarding the pull request, it's cool to give credit for a modification I think so no problem ;-)

**Comment by emericg** [comment]
Ok this is merged! Turned out it's not possible to edit the pull request, so I did revert the fix on the SmartServoGui.pro "manually".
Thanks again, and I'll try to test the mac build this weekend!

**Pull request merged**
